# Generated by Django 3.1 on 2020-10-24 07:28

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=storeapp.models.uploadprofileimage_path),
        ),
    ]
