# Generated by Django 3.1 on 2020-10-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_categories_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
