# Generated by Django 3.1 on 2020-10-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_auto_20201029_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category',
            new_name='category_id',
        ),
    ]
