# Generated by Django 3.1 on 2020-11-04 07:30

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=storeapp.models.uploadcategoryimage_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=storeapp.models.uploadprofileimage_path),
        ),
    ]
